# WaveRider configuration

odom_frame: "base_line"
goal_tf_frame: "waverider_goal"
ground_plane_tf_frame: "world"
tf_lookup_delay: { seconds: 0.05 }
occupancy_threshold: 0.1
control_period: { seconds: 0.02 }
integrator_step_size: { seconds: 0.005 }
publish_debug_visuals_every_n_iterations: 20
ground_plane_offset: { meters: 0.10 }
goal_policy:
  alpha: 25.0
  beta: 35.0
  c: 0.2
  a: 20.0
yaw_policy:
  alpha: 15.0
  beta: 20.0
  c: 0.1
  a: 20.0
  angle_forward: { degrees: 180.0 }
map_obstacles_policy:
  c: 0.1
  eta_rep: 30.0
  eta_damp: 340.0
  enable_damper: true
  enable_repulsor: true
aabb_obstacles_policy:
  r: 160.0         # overall activation strenght
  eta_rep: 500.0   # linear repulsion term
  eta_damp: 300.0  # damping -> based on robot velocity to obstacle
  enable_damper: true
  enable_repulsor: true