# NOTE: More examples can be found in the `interfaces/ros1/wavemap_ros/config`
#       directory, and all available params are documented at:
#       https://ethz-asl.github.io/wavemap/pages/parameters

map:
  type: hashed_wavelet_octree
  min_cell_width: { meters: 0.1 }

map_operations:
  - type: threshold_map
    once_every: { seconds: 5.0 }
  - type: prune_map
    once_every: { seconds: 10.0 }
  - type: crop_map
    once_every: { seconds: 0.1 }
    remove_blocks_beyond_distance: { meters: 7.0 }
    only_when_moved: { meters: 5.0 }

measurement_integrators:
  gazebo_short:
    projection_model:
      type: pinhole_camera_projector
      width: 640
      height: 480
      fx: 387.2292480468
      fy: 387.2292480468
      cx: 320.0
      cy: 240.0
    measurement_model:
      type: continuous_ray
      range_sigma: { meters: 0.08 }
      scaling_free: 0.3
      scaling_occupied: 0.6
    integration_method:
      type: hashed_wavelet_integrator
      min_range: { meters: 0.3 }
      max_range: { meters: 12.0 }
      max_update_resolution: { meters: 0.1 }

#  gazebo_long:
#    projection_model:
#      type: pinhole_camera_projector
#      width: 640
#      height: 480
#      fx: 387.2292480468
#      fy: 387.2292480468
#      cx: 320.0
#      cy: 240.0
#    measurement_model:
#      type: continuous_ray
#      range_sigma: { meters: 0.1 }
#      scaling_free: 0.3
#      scaling_occupied: 0.6
#    integration_method:
#      type: hashed_wavelet_integrator
#      min_range: { meters: 10.0 }
#      max_range: { meters: 20.0 }
#      max_update_resolution: { meters: 0.5 }
